apiVersion: v1
kind: Service
metadata:
  name: eladmin-api
  namespace: yu
spec:
  selector:
    app: eladmin-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

