apiVersion: apps/v1
kind: Deployment
metadata:
  name: eladmin-api
  namespace: yu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eladmin-api
  template:
    metadata:
      labels:
        app: eladmin-api
    spec:
      containers:
      - name: eladmin-api
        image: maweika/eladmin-api:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: mysql.yu.svc.cluster.local
        - name: REDIS_HOST
          value: redis.yu.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: DB_USER
          value: root
        - name: DB_PWD
          value: root
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /auth/code
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 15

