apiVersion: apps/v1
kind: Deployment
metadata:
  name: eladmin-web
  namespace: yu
  labels:
    app: eladmin-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eladmin-web
  template:
    metadata:
      labels:
        app: eladmin-web
    spec:
      containers:
      - name: web
        image: maweika/eladmin-web:v3
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

