apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eladmin-api
  namespace: yu
spec:
  ingressClassName: nginx
  rules:
    - host: eladmin-api.yuchao.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eladmin-api
                port:
                  number: 8000

