apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: yu
spec:
  selector:
    app: mysql  # ← 必须和 Deployment 中的 labels 一致！
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
